
# ==============================================================================
# AGENT TASK DEFINITION: Deploy Project to Railway
# FORMAT: YAML for AI Agent Consumption
# ==============================================================================

plan_name: railway_deployment_workflow
target_platform: Railway
trigger: on_git_push
source_repo: "User-provided GitHub repository"

phases:
  - phase_name: "Phase 1: Initial Provisioning"
    description: "One-time setup of accounts and services."
    tasks:
      - task_id: 1.1
        description: "Create Railway account using GitHub OAuth."
        tool: BROWSER
        action: navigate_and_authenticate
        parameters:
          url: "https://railway.app/login"
          auth_method: "github_oauth"
        output: "variable:railway_auth_cookie"
        dependencies: []

      - task_id: 1.2
        description: "Ensure project code is available in a GitHub repository."
        tool: GIT_API
        action: get_repo_status
        parameters:
          repo_url: "{{source_repo}}"
        output: "status:repo_exists"
        dependencies: []

      - task_id: 1.3
        description: "Create a new empty project on Railway."
        tool: RAILWAY_API
        action: create_project
        parameters:
          project_name: "autodeploy-project"
        output: "variable:railway_project_id"
        dependencies: [1.1]

      - task_id: 1.4
        description: "Provision a PostgreSQL database within the Railway project."
        tool: RAILWAY_API
        action: create_service
        parameters:
          project_id: "{{railway_project_id}}"
          service_type: "postgresql"
        output: "variable:db_service_id"
        dependencies: [1.3]

      - task_id: 1.5
        description: "Create an empty service for the web application."
        tool: RAILWAY_API
        action: create_service
        parameters:
          project_id: "{{railway_project_id}}"
          service_type: "empty"
          service_name: "portfolio-prod"
        output: "variable:web_service_id"
        dependencies: [1.3]

  - phase_name: "Phase 2: Secret and Configuration Gathering"
    description: "Collect all necessary credentials and variables for deployment."
    tasks:
      - task_id: 2.1
        description: "Retrieve DATABASE_URL from the provisioned PostgreSQL service."
        tool: RAILWAY_API
        action: get_variable
        parameters:
          project_id: "{{railway_project_id}}"
          service_id: "{{db_service_id}}"
          variable_name: "DATABASE_URL"
        output: "secret:DATABASE_URL"
        dependencies: [1.4]

      - task_id: 2.2
        description: "Generate a secure Django SECRET_KEY."
        tool: CRYPTO_GENERATOR
        action: generate_random_string
        parameters:
          length: 50
          charset: "alphanumeric_special"
        output: "secret:SECRET_KEY"
        dependencies: []

      - task_id: 2.3
        description: "Create a Railway API token for GitHub Actions."
        tool: RAILWAY_API
        action: create_api_token
        parameters:
          token_name: "github-actions-deploy-token"
        output: "secret:RAILWAY_TOKEN"
        dependencies: [1.1]

  - phase_name: "Phase 3: Configure GitHub Secrets"
    description: "Inject the gathered secrets into the GitHub repository for Actions."
    tasks:
      - task_id: 3.1
        description: "Set all required secrets in the GitHub repository settings."
        tool: GITHUB_API
        action: set_repo_secrets
        parameters:
          repo_url: "{{source_repo}}"
          secrets:
            - name: "RAILWAY_TOKEN"
              value: "{{secret:RAILWAY_TOKEN}}"
            - name: "DATABASE_URL"
              value: "{{secret:DATABASE_URL}}"
            - name: "SECRET_KEY"
              value: "{{secret:SECRET_KEY}}"
        output: "status:secrets_configured"
        dependencies: [2.1, 2.2, 2.3]

  - phase_name: "Phase 4: Trigger and Monitor Deployment"
    description: "Initiate the deployment workflow and verify its execution."
    tasks:
      - task_id: 4.1
        description: "Verify the service name in the workflow file matches the provisioned service."
        tool: FILE_SYSTEM
        action: read_and_verify
        parameters:
          file_path: ".github/workflows/deploy-advanced.yml"
          search_pattern: "service=portfolio-prod"
        output: "status:workflow_sane"
        dependencies: [1.5]

      - task_id: 4.2
        description: "Trigger the workflow by pushing a commit to the main branch."
        tool: GIT_CLI
        action: push_commit
        parameters:
          repo_path: "."
          commit_message: "chore: trigger initial deployment"
          branch: "main"
        output: "variable:workflow_run_id"
        dependencies: [3.1, 4.1]

      - task_id: 4.3
        description: "Monitor the GitHub Actions workflow until completion."
        tool: GITHUB_API
        action: get_workflow_status
        parameters:
          run_id: "{{workflow_run_id}}"
        output: "variable:deployment_status"
        dependencies: [4.2]

  - phase_name: "Phase 5: Post-Deployment Verification"
    description: "Verify the application is live and functional."
    tasks:
      - task_id: 5.1
        description: "Retrieve the live deployment URL from Railway."
        tool: RAILWAY_API
        action: get_service_domain
        parameters:
          project_id: "{{railway_project_id}}"
          service_id: "{{web_service_id}}"
        output: "variable:live_url"
        dependencies: [4.3]

      - task_id: 5.2
        description: "Perform an HTTP health check on the live URL."
        tool: HTTP_CLIENT
        action: get
        parameters:
          url: "{{live_url}}/health/" # Assuming a health check endpoint
        output: "status:health_check_passed"
        dependencies: [5.1]

      - task_id: 5.3
        description: "Final report generation."
        tool: REPORTING
        action: generate_summary
        parameters:
          status: "{{deployment_status}}"
          url: "{{live_url}}"
        output: "status:done"
        dependencies: [5.2]
