/* eslint-env node */
// ESLint v9 flat config format (CommonJS)
// https://eslint.org/docs/latest/use/configure/configuration-files-new

module.exports = [
    {
        ignores: [
            '**/node_modules/**',
            '**/staticfiles/**',
            '**/static/CACHE/**',
            '**/dist/**',
            '**/build/**',
            '**/*.min.js',
            '**/vendor/**',
            '**/__pycache__/**',
            '**/migrations/**',
            'scripts/**/*.js',
            'tests/**/*.js',
            'tailwind.config.js',
            'webpack.config.js',
            'jest.config.js',
            'postcss.config.js',
            'playwright.config.js',
            '**/.venv/**',
            '**/venv/**',
            '**/site-packages/**',
        ],
    },
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                // Browser globals
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
                console: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                fetch: 'readonly',
                FormData: 'readonly',
                URLSearchParams: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                requestIdleCallback: 'readonly',
                performance: 'readonly',
                PerformanceObserver: 'readonly',
                ResizeObserver: 'readonly',
                location: 'readonly',
                history: 'readonly',
                URL: 'readonly',
                Image: 'readonly',
                Event: 'readonly',
                CustomEvent: 'readonly',
                IntersectionObserver: 'readonly',
                FontFace: 'readonly',
                Request: 'readonly',
                Response: 'readonly',
                MessageChannel: 'readonly',
                // Django/Alpine.js globals
                Alpine: 'readonly',
                django: 'readonly',
                gettext: 'readonly',
                ngettext: 'readonly',
                interpolate: 'readonly',
                // Service Worker
                self: 'readonly',
                caches: 'readonly',
                clients: 'readonly',
                workbox: 'readonly',
                // Node.js/CommonJS globals
                require: 'readonly',
                module: 'writable',
                exports: 'writable',
                process: 'readonly',
                global: 'readonly',
                __dirname: 'readonly',
                __filename: 'readonly',
                Buffer: 'readonly',
                setImmediate: 'readonly',
                clearImmediate: 'readonly',
            },
        },
        rules: {
            // Possible Errors
            'no-console': ['warn', { allow: ['warn', 'error', 'log', 'info', 'debug'] }],
            'no-debugger': 'warn',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-empty': ['error', { allowEmptyCatch: true }],
            'no-ex-assign': 'error',
            'no-extra-boolean-cast': 'error',
            'no-func-assign': 'error',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'error',
            'no-obj-calls': 'error',
            'no-sparse-arrays': 'error',
            'no-unexpected-multiline': 'error',
            'no-unreachable': 'error',
            'use-isnan': 'error',
            'valid-typeof': 'error',

            // Best Practices
            'curly': ['error', 'all'],
            'eqeqeq': ['error', 'always', { null: 'ignore' }],
            'no-caller': 'error',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-implied-eval': 'error',
            'no-iterator': 'error',
            'no-lone-blocks': 'error',
            'no-loop-func': 'error',
            'no-multi-spaces': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-octal': 'error',
            'no-redeclare': 'error',
            'no-script-url': 'error',
            'no-self-compare': 'error',
            'no-sequences': 'error',
            'no-unused-expressions': ['error', { allowShortCircuit: true, allowTernary: true }],
            'no-useless-call': 'error',
            'no-useless-concat': 'error',
            'no-with': 'error',
            'radix': 'error',
            'wrap-iife': ['error', 'inside'],

            // Variables
            'no-delete-var': 'error',
            'no-label-var': 'error',
            'no-shadow-restricted-names': 'error',
            'no-undef': 'error',
            'no-undef-init': 'error',
            'no-unused-vars': ['warn', {
                vars: 'all',
                args: 'after-used',
                ignoreRestSiblings: true,
                argsIgnorePattern: '^_',
                varsIgnorePattern: '^_',
            }],

            // Stylistic Issues
            'array-bracket-spacing': ['error', 'never'],
            'block-spacing': ['error', 'always'],
            'brace-style': ['error', '1tbs', { allowSingleLine: true }],
            'comma-dangle': ['error', 'only-multiline'],
            'comma-spacing': ['error', { before: false, after: true }],
            'comma-style': ['error', 'last'],
            'computed-property-spacing': ['error', 'never'],
            'func-call-spacing': ['error', 'never'],
            'indent': ['error', 4, { SwitchCase: 1 }],
            'key-spacing': ['error', { beforeColon: false, afterColon: true }],
            'keyword-spacing': ['error', { before: true, after: true }],
            'linebreak-style': ['error', 'unix'],
            'no-mixed-spaces-and-tabs': 'error',
            'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1 }],
            'no-trailing-spaces': 'error',
            'object-curly-spacing': ['error', 'always'],
            'quotes': ['error', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
            'semi': ['error', 'always'],
            'semi-spacing': ['error', { before: false, after: true }],
            'space-before-blocks': ['error', 'always'],
            'space-before-function-paren': ['error', { anonymous: 'always', named: 'never', asyncArrow: 'always' }],
            'space-in-parens': ['error', 'never'],
            'space-infix-ops': 'error',
            'space-unary-ops': ['error', { words: true, nonwords: false }],

            // ES6
            'arrow-body-style': ['error', 'as-needed'],
            'arrow-parens': ['error', 'as-needed'],
            'arrow-spacing': ['error', { before: true, after: true }],
            'no-duplicate-imports': 'error',
            'no-useless-computed-key': 'error',
            'no-useless-constructor': 'error',
            'no-useless-rename': 'error',
            'no-var': 'error',
            'prefer-const': ['error', { destructuring: 'all' }],
            'prefer-template': 'error',
            'template-curly-spacing': ['error', 'never'],
        },
    },
];
