# Generated by Django 5.2.5 on 2025-08-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_post_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='URL to a featured image for this post', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload a featured image for this post', null=True, upload_to='blog/images/'),
        ),
    ]
