# Generated by Django 5.1 on 2025-09-15 12:28

import apps.main.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_remove_tool_documentation_url_remove_tool_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image/screenshot for this tool', null=True, upload_to='tools/', validators=[apps.main.file_validators.ImageValidator(max_size=5242880)]),
        ),
    ]
