# Generated by Django 5.1 on 2025-11-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0006_alter_tool_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of title",
                max_length=255,
                unique=True,
            ),
        ),
    ]
