# Generated by Django 5.1 on 2025-11-12 19:17

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Generate slugs for existing Tool records"""
    Tool = apps.get_model('tools', 'Tool')
    for tool in Tool.objects.all():
        if not tool.slug:
            base_slug = slugify(tool.title)
            slug = base_slug
            counter = 1
            # Ensure uniqueness
            while Tool.objects.filter(slug=slug).exclude(pk=tool.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            tool.slug = slug
            tool.save()


def reverse_populate_slugs(apps, schema_editor):
    """Remove slugs (for rollback)"""
    Tool = apps.get_model('tools', 'Tool')
    Tool.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0007_add_slug_field"),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
