# Generated by Django 5.1 on 2025-11-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0008_populate_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this tool has been viewed"
            ),
        ),
    ]
