# Generated by Django 5.1 on 2025-11-12 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contactmessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="preferred_channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("calendly", "Plan a call"),
                    ("slack", "Slack / Teams invite"),
                ],
                default="email",
                help_text="Preferred response channel",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(
                help_text="Valid email address",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(
                help_text="Message content (10-2000 characters)",
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(
                help_text="Full name (2-100 characters)",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(
                help_text="Message subject (3-200 characters)",
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
