# Generated by Django 5.1 on 2025-09-15 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_series_remove_post_featured_image_alt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_author__3a3e8e_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_status_pub',
            old_name='blog_post_status_615533_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_slug',
            old_name='blog_post_slug_cdb902_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-created_at'], name='blog_status_created'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'status', '-published_at'], name='blog_auth_stat_pub'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status'], name='blog_status'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at'], name='blog_pub_desc'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='blog_created_desc'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-updated_at'], name='blog_updated_desc'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'author', '-view_count'], name='blog_pop_by_author'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-view_count'], name='blog_popular'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('tags__isnull', False)), fields=['status', '-published_at'], name='blog_tagged_pub'),
        ),
    ]
