# Generated by Django 5.1 on 2025-09-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_blog_post_author__3a3e8e_idx_and_more'),
        ('main', '0011_remove_skill_certificates_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_status_created',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_auth_stat_pub',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_status',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_pub_desc',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_created_desc',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_updated_desc',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_pop_by_author',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_popular',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_tagged_pub',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_status_615533_idx',
            old_name='blog_status_pub',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_slug_cdb902_idx',
            old_name='blog_slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Author of this post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.admin'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-published_at'], name='blog_post_author__3a3e8e_idx'),
        ),
    ]
