# Generated by Django 5.1 on 2025-11-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '9999_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='idx_blog_post_slug',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='idx_blog_post_status_dates',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='idx_blog_post_author_status',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='idx_blog_post_views',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='idx_blog_post_created',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='idx_blog_post_updated',
        ),
    ]
