# Generated by Django 5.2.5 on 2025-09-02 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_featured_image_url_alter_post_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog series', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this series covers')),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the series', null=True, upload_to='blog/series/')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this series is complete')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this series is visible to the public')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Series',
                'verbose_name_plural': 'Blog Series',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='series_order',
            field=models.PositiveIntegerField(default=0, help_text='Order within the series (0 = first post)'),
        ),
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Blog series this post belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogseries'),
        ),
    ]
