# Generated by Django 5.2.5 on 2025-09-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogseries_post_series_order_post_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the featured image (SEO & accessibility)', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('article', 'Article'), ('tutorial', 'Tutorial'), ('review', 'Review'), ('news', 'News'), ('case_study', 'Case Study'), ('guide', 'Guide'), ('opinion', 'Opinion'), ('interview', 'Interview')], default='article', help_text='Type of blog post content', max_length=20),
        ),
    ]
