# Generated by Django 5.1 on 2025-09-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_featured_image_alt_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='Main content of the blog post (supports Markdown and HTML)', null=True),
        ),
    ]
