# Generated by Django 5.2.5 on 2025-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='series',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured_image_alt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='series_order',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='Main content of the blog post (supports Markdown)', null=True),
        ),
        migrations.DeleteModel(
            name='BlogSeries',
        ),
    ]
