"""
Django settings for portfolio_site project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-l994t=sodtt9oysm+#s9qkuh=r42mlt4rx_*d55+tj_u2xy&0m"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "testserver", ".railway.app", "*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "rest_framework",
    "tinymce",
    "apps.portfolio.apps.PortfolioConfig",
    "main.apps.MainConfig",
    "blog",
    "tools",
    "contact",
    "chat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.core.middleware.rate_limiting.RateLimitMiddleware",  # Rate limiting for auth
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "portfolio_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.social_links",
            ],
        },
    },
]

WSGI_APPLICATION = "portfolio_site.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation (moved to SECURITY SETTINGS section below)
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "main.Admin"

# Authentication backend - restricted admin only via environment variables
AUTHENTICATION_BACKENDS = [
    "apps.main.auth_backends.RestrictedAdminBackend",
]

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "portfolio-cache",
        "TIMEOUT": 300,
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
            "CULL_FREQUENCY": 3,
        },
    }
}

# Email Configuration
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_HOST = ""
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
DEFAULT_FROM_EMAIL = "bugraakin01@gmail.com"

# ==============================================================================
# SECURITY SETTINGS - OWASP Top 10 & Best Practices
# ==============================================================================

# SSL/HTTPS Security (Enable in production)
SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "False") == "True"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# HTTP Strict Transport Security (HSTS)
SECURE_HSTS_SECONDS = int(
    os.environ.get("SECURE_HSTS_SECONDS", "0")
)  # 31536000 in prod (1 year)
SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    os.environ.get("SECURE_HSTS_INCLUDE_SUBDOMAINS", "False") == "True"
)
SECURE_HSTS_PRELOAD = os.environ.get("SECURE_HSTS_PRELOAD", "False") == "True"

# Cookie Security
SESSION_COOKIE_SECURE = (
    os.environ.get("SESSION_COOKIE_SECURE", "False") == "True"
)  # True in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
SESSION_COOKIE_SAMESITE = "Lax"  # CSRF protection
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

CSRF_COOKIE_SECURE = (
    os.environ.get("CSRF_COOKIE_SECURE", "False") == "True"
)  # True in production
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_USE_SESSIONS = False
CSRF_COOKIE_AGE = 31449600  # 1 year

# XSS & Content Type Protection
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Clickjacking Protection
X_FRAME_OPTIONS = "DENY"

# Content Security Policy (CSP) - Will be configured via middleware
# See: apps/core/middleware/security_headers.py for implementation

# Password Policy
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 12,  # Increased from Django default (8)
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Rate Limiting Configuration
RATE_LIMIT_CONFIG = {
    "MAX_LOGIN_ATTEMPTS": int(os.environ.get("RATE_LIMIT_MAX_ATTEMPTS", "5")),
    "LOCKOUT_DURATION": int(
        os.environ.get("RATE_LIMIT_LOCKOUT_DURATION", "900")
    ),  # 15 min
    "ATTEMPT_WINDOW": int(os.environ.get("RATE_LIMIT_ATTEMPT_WINDOW", "300")),  # 5 min
    "ENABLE_IP_TRACKING": True,
    "ENABLE_USERNAME_TRACKING": True,
    "EXEMPT_IPS": ["127.0.0.1", "localhost"],
}

RATE_LIMIT_PATHS = [
    "/admin/login/",
    "/api/auth/login/",
    "/api/auth/token/",
    "/accounts/login/",
    "/password-reset/",
    "/api/auth/register/",
]

# Admin Configuration
ADMIN_URL = os.environ.get("ADMIN_URL", "admin/")  # Obfuscate in production

# Static files
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# TinyMCE Configuration for Rich Text Editing
TINYMCE_DEFAULT_CONFIG = {
    "height": 500,
    "width": "100%",
    "plugins": [
        "advlist",
        "autolink",
        "lists",
        "link",
        "image",
        "charmap",
        "preview",
        "anchor",
        "searchreplace",
        "visualblocks",
        "code",
        "fullscreen",
        "insertdatetime",
        "media",
        "table",
        "help",
        "wordcount",
        "codesample",
        "emoticons",
        "textcolor",
        "paste",
        "autosave",
    ],
    "toolbar": "undo redo | formatselect | bold italic backcolor forecolor | "
    + "alignleft aligncenter alignright alignjustify | "
    + "bullist numlist outdent indent | removeformat | "
    + "link image media table codesample | "
    + "searchreplace | fullscreen | emoticons | help",
    "menubar": "file edit view insert format tools table help",
    "toolbar_mode": "sliding",
    "statusbar": True,
    "relative_urls": False,
    "automatic_uploads": True,
    "file_picker_types": "file image media",
    "images_upload_url": "/api/upload/images/",
    "codesample_languages": [
        {"text": "Python", "value": "python"},
        {"text": "JavaScript", "value": "javascript"},
        {"text": "HTML", "value": "html"},
        {"text": "CSS", "value": "css"},
        {"text": "SQL", "value": "sql"},
        {"text": "Bash", "value": "bash"},
    ],
    "license_key": "gpl",  # Use GPL for open source
}

# Content Management Settings
CONTENT_SANITIZATION = {
    "ENABLED": True,
    "ALLOWED_TAGS": [
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "p",
        "br",
        "hr",
        "strong",
        "em",
        "u",
        "s",
        "code",
        "a",
        "img",
        "ul",
        "ol",
        "li",
        "blockquote",
        "pre",
        "table",
        "thead",
        "tbody",
        "tr",
        "th",
        "td",
        "div",
        "span",
    ],
    "STRIP_JAVASCRIPT": True,
    "VERIFY_LINKS": True,
}

# MeiliSearch Configuration
MEILISEARCH_HOST = os.environ.get("MEILI_HOST", "http://localhost:7700")
MEILISEARCH_MASTER_KEY = os.environ.get("MEILI_MASTER_KEY", "masterKey123456789")
MEILISEARCH_INDEX_NAME = os.environ.get("MEILI_INDEX_NAME", "portfolio_search")
MEILISEARCH_TIMEOUT = 5  # seconds
MEILISEARCH_BATCH_SIZE = 100  # documents per batch
