# Generated by Django 5.2.5 on 2025-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_admin_options_alter_personalinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(help_text='URL to your profile or email address', max_length=255),
        ),
    ]
