# Generated by Django 5.2.5 on 2025-09-02 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_current_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['order', 'display_name'], 'verbose_name': 'Blog Kategorisi', 'verbose_name_plural': 'Blog Kategorileri'},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Yorum İzni'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='background_color',
            field=models.CharField(default='#1E3A8A', max_length=7, verbose_name='Arkaplan Rengi (Hex)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_categories/', verbose_name='Kapak Görseli'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='default_content_type',
            field=models.CharField(choices=[('tutorial', 'Eğitim'), ('guide', 'Kılavuz'), ('review', 'İnceleme'), ('news', 'Haber'), ('opinion', 'Görüş'), ('case_study', 'Vaka Analizi'), ('interview', 'Röportaj'), ('list', 'Liste'), ('comparison', 'Karşılaştırma'), ('deep_dive', 'Derinlemesine Analiz'), ('quick_tip', 'Hızlı İpucu'), ('announcement', 'Duyuru'), ('story', 'Hikaye'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Varsayılan İçerik Türü'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, verbose_name='Emoji'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkarılsın mı?'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='is_newsletter_included',
            field=models.BooleanField(default=True, verbose_name="Newsletter'a Dahil Et"),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Anahtar Kelimeler (virgülle ayrılmış)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='SEO Açıklama'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='SEO Başlık'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='main.blogcategory', verbose_name='Ana Kategori'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='post_count',
            field=models.IntegerField(default=0, verbose_name='Yazı Sayısı'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='require_approval',
            field=models.BooleanField(default=False, verbose_name='Yayın Onayı Gerekli'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name='Menüde Göster'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='show_in_sidebar',
            field=models.BooleanField(default=True, verbose_name='Kenar Çubuğunda Göster'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='subscriber_count',
            field=models.IntegerField(default=0, verbose_name='Abone Sayısı'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7, verbose_name='Renk (Hex)'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='display_name',
            field=models.CharField(max_length=100, verbose_name='Görüntülenen Ad'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ikon (CSS class veya emoji)'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Görünür mü?'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(choices=[('programming', 'Programlama'), ('web_development', 'Web Geliştirme'), ('cybersecurity', 'Siber Güvenlik'), ('ai_ml', 'Yapay Zeka & ML'), ('devops', 'DevOps'), ('mobile', 'Mobil Geliştirme'), ('database', 'Veritabanı'), ('cloud', 'Bulut Teknolojileri'), ('blockchain', 'Blockchain'), ('iot', 'IoT & Embedded'), ('game_dev', 'Oyun Geliştirme'), ('data_science', 'Veri Bilimi'), ('ui_ux', 'UI/UX Tasarım'), ('project_management', 'Proje Yönetimi'), ('career', 'Kariyer'), ('learning', 'Öğrenme'), ('productivity', 'Verimlilik'), ('tools', 'Araçlar'), ('tutorials', 'Eğitimler'), ('reviews', 'İncelemeler'), ('news', 'Haberler'), ('thoughts', 'Düşünceler'), ('experiences', 'Deneyimler'), ('challenges', 'Zorluklarla Başa Çıkma'), ('open_source', 'Açık Kaynak'), ('freelancing', 'Freelancing'), ('startup', 'Startup'), ('industry', 'Sektör'), ('events', 'Etkinlikler'), ('books', 'Kitaplar'), ('philosophy', 'Felsefe'), ('personal', 'Kişisel'), ('other', 'Diğer')], max_length=50, unique=True, verbose_name='Kategori Kodu'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
