# Generated by Django 5.2.5 on 2025-08-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin User', 'verbose_name_plural': 'Admin Users'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'ordering': ['order', 'key'], 'verbose_name': 'Personal Information', 'verbose_name_plural': 'Personal Information'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['order', 'platform'], 'verbose_name': 'Social Link', 'verbose_name_plural': 'Social Links'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(help_text='Display name for the portfolio', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Whether this information is visible on the site'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='key',
            field=models.CharField(help_text='Unique identifier for this information', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('json', 'JSON'), ('markdown', 'Markdown'), ('html', 'HTML')], default='text', help_text='How this content should be rendered', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='value',
            field=models.TextField(help_text='The content/value of this information'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this social link', null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark as primary/main social link'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Whether this link is visible on the site'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('website', 'Website'), ('other', 'Other')], help_text='Social media platform', max_length=50),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='stats',
            field=models.JSONField(blank=True, help_text='JSON data for follower counts, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(help_text='Full URL to your profile'),
        ),
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together={('platform', 'url')},
        ),
    ]
