# Generated by Django 5.2.5 on 2025-08-27 15:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aitool_cybersecurityresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('philosophy', 'Felsefe'), ('history', 'Tarih'), ('sociology', 'Sosyoloji'), ('technology', 'Teknoloji'), ('personal', 'Kişisel'), ('other', 'Diğer')], help_text='Blog kategorisi', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Görüntülenecek kategori adı', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Kategori açıklaması')),
                ('color', models.CharField(default='#3B82F6', help_text='Kategori rengi (hex kod)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Kategori ikonu (CSS class veya emoji)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Sıralama')),
                ('is_visible', models.BooleanField(default=True, help_text='Site üzerinde görünür mü?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='MusicPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Playlist adı', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Playlist açıklaması')),
                ('platform', models.CharField(choices=[('spotify', 'Spotify'), ('youtube', 'YouTube Music'), ('apple', 'Apple Music'), ('soundcloud', 'SoundCloud'), ('other', 'Diğer')], default='spotify', help_text='Müzik platformu', max_length=20)),
                ('url', models.URLField(help_text="Playlist URL'si")),
                ('embed_url', models.URLField(blank=True, help_text='Embed için URL (otomatik oluşturulur)')),
                ('cover_image', models.URLField(blank=True, help_text="Playlist kapak görseli URL'si")),
                ('track_count', models.IntegerField(default=0, help_text='Şarkı sayısı')),
                ('is_featured', models.BooleanField(default=False, help_text='Öne çıkan playlist olarak işaretle')),
                ('order', models.IntegerField(default=0, help_text='Sıralama')),
                ('is_visible', models.BooleanField(default=True, help_text='Site üzerinde görünür mü?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Music Playlist',
                'verbose_name_plural': 'Music Playlists',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpotifyCurrentTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(help_text='Şarkı adı', max_length=200)),
                ('artist_name', models.CharField(help_text='Sanatçı adı', max_length=200)),
                ('album_name', models.CharField(blank=True, help_text='Albüm adı', max_length=200)),
                ('track_url', models.URLField(blank=True, help_text="Spotify şarkı URL'si")),
                ('image_url', models.URLField(blank=True, help_text="Albüm kapağı URL'si")),
                ('is_playing', models.BooleanField(default=False, help_text='Şu an çalıyor mu?')),
                ('progress_ms', models.IntegerField(default=0, help_text='Çalma ilerlemesi (milisaniye)')),
                ('duration_ms', models.IntegerField(default=0, help_text='Şarkı süresi (milisaniye)')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Son güncelleme')),
            ],
            options={
                'verbose_name': 'Spotify Current Track',
                'verbose_name_plural': 'Spotify Current Track',
                'get_latest_by': 'last_updated',
            },
        ),
        migrations.CreateModel(
            name='UsefulResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kaynak adı', max_length=100)),
                ('description', models.TextField(help_text='Kaynak açıklaması')),
                ('url', models.URLField(help_text="Kaynak URL'si")),
                ('type', models.CharField(choices=[('website', 'Website'), ('app', 'Uygulama'), ('tool', 'Araç'), ('extension', 'Tarayıcı Eklentisi'), ('other', 'Diğer')], default='website', help_text='Kaynak türü', max_length=20)),
                ('category', models.CharField(choices=[('development', 'Geliştirme'), ('design', 'Tasarım'), ('productivity', 'Verimlilik'), ('ai', 'Yapay Zeka'), ('learning', 'Öğrenme'), ('entertainment', 'Eğlence'), ('utility', 'Yardımcı Programlar'), ('other', 'Diğer')], default='utility', help_text='Kaynak kategorisi', max_length=20)),
                ('icon_url', models.URLField(blank=True, help_text="Kaynak ikonu URL'si", null=True)),
                ('image', models.ImageField(blank=True, help_text='Kaynak görseli', null=True, upload_to='useful_resources/')),
                ('is_free', models.BooleanField(default=True, help_text='Ücretsiz mi?')),
                ('is_featured', models.BooleanField(default=False, help_text='Öne çıkan kaynak olarak işaretle')),
                ('rating', models.FloatField(default=0.0, help_text='Kişisel değerlendirme (0-5)')),
                ('tags', models.CharField(blank=True, help_text='Virgülle ayrılmış etiketler', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Sıralama')),
                ('is_visible', models.BooleanField(default=True, help_text='Site üzerinde görünür mü?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Useful Resource',
                'verbose_name_plural': 'Useful Resources',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog yazısının başlığı', max_length=200)),
                ('slug', models.SlugField(help_text='URL için benzersiz slug (otomatik oluşturulur)', max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Kısa özet (300 karakter)', max_length=300)),
                ('content', models.TextField(help_text='Ana içerik (Markdown destekli)')),
                ('featured_image', models.ImageField(blank=True, help_text='Öne çıkan görsel', null=True, upload_to='blog_posts/')),
                ('tags', models.CharField(blank=True, help_text='Virgülle ayrılmış etiketler', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayınlandı'), ('archived', 'Arşivlendi')], default='draft', help_text='Yazı durumu', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Öne çıkan yazı olarak işaretle')),
                ('reading_time', models.IntegerField(default=0, help_text='Tahmini okuma süresi (dakika)')),
                ('view_count', models.IntegerField(default=0, help_text='Görüntülenme sayısı')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta açıklama', max_length=160)),
                ('published_at', models.DateTimeField(blank=True, help_text='Yayınlanma tarihi', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Yazı sahibi', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Blog yazısının kategorisi', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
