# Generated by Django 5.2.5 on 2025-09-02 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_certificate_shorturl_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Aktivite Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('activity_type', models.CharField(choices=[('coding', 'Kodlama'), ('learning', 'Öğrenme'), ('reading', 'Okuma'), ('project', 'Proje'), ('work', 'İş'), ('music', 'Müzik'), ('gaming', 'Oyun'), ('social', 'Sosyal'), ('travel', 'Seyahat'), ('exercise', 'Spor'), ('food', 'Yemek'), ('rest', 'Dinlenme'), ('other', 'Diğer')], max_length=20, verbose_name='Aktivite Türü')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('paused', 'Duraklatıldı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='active', max_length=20, verbose_name='Durum')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='Tamamlanma Oranı (%)')),
                ('priority', models.IntegerField(choices=[(1, 'Düşük'), (2, 'Normal'), (3, 'Yüksek'), (4, 'Acil'), (5, 'Kritik')], default=2, verbose_name='Öncelik Seviyesi')),
                ('start_time', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='Tahmini Süre')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Konum')),
                ('mood', models.CharField(blank=True, max_length=50, verbose_name='Ruh Hali')),
                ('energy_level', models.IntegerField(choices=[(1, 'Çok Düşük'), (2, 'Düşük'), (3, 'Normal'), (4, 'Yüksek'), (5, 'Çok Yüksek')], default=3, verbose_name='Enerji Seviyesi')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Renk (Hex)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='Aktivite Görseli')),
                ('related_url', models.URLField(blank=True, verbose_name='İlgili URL')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Etiketler (virgülle ayrılmış)')),
                ('share_on_social', models.BooleanField(default=False, verbose_name='Sosyal Medyada Paylaş')),
                ('is_public', models.BooleanField(default=True, verbose_name='Herkese Açık')),
                ('auto_update_status', models.BooleanField(default=False, verbose_name='Otomatik Durum Güncellemesi')),
                ('last_update_source', models.CharField(blank=True, max_length=50, verbose_name='Son Güncelleme Kaynağı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project', verbose_name='İlgili Proje')),
            ],
            options={
                'verbose_name': 'Güncel Aktivite',
                'verbose_name_plural': 'Güncel Aktiviteler',
                'ordering': ['-start_time', '-priority'],
            },
        ),
    ]
