# Generated by Django 5.2.5 on 2025-09-05 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0010_blog_category_expansion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='currentactivity',
            name='related_project',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='related_projects',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['order', 'display_name'], 'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='allow_comments',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='default_content_type',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='is_newsletter_included',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='post_count',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='require_approval',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='show_in_menu',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='show_in_sidebar',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='subscriber_count',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='admin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='admin_set', related_query_name='admin', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='admin_set', related_query_name='admin', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Kategori rengi (hex kod)', max_length=7),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Kategori açıklaması'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='display_name',
            field=models.CharField(help_text='Görüntülenecek kategori adı', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Kategori ikonu (CSS class veya emoji)', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Site üzerinde görünür mü?'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(choices=[('philosophy', 'Felsefe'), ('history', 'Tarih'), ('sociology', 'Sosyoloji'), ('technology', 'Teknoloji'), ('personal', 'Kişisel'), ('other', 'Diğer')], help_text='Blog kategorisi', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Sıralama'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='CurrentActivity',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ShortURL',
        ),
    ]
