# Generated by Django 5.1 on 2025-09-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0011_remove_skill_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='admin_users', related_query_name='admin_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='admin_users', related_query_name='admin_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(help_text='Yazı sahibi', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='main.admin'),
        ),
    ]
