# Generated by Django 5.1 on 2025-11-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '9999_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='admin',
            name='idx_main_admin_email',
        ),
        migrations.RemoveIndex(
            model_name='admin',
            name='idx_main_admin_active',
        ),
        migrations.RemoveIndex(
            model_name='aitool',
            name='idx_aitool_category_visible',
        ),
        migrations.RemoveIndex(
            model_name='aitool',
            name='idx_aitool_featured',
        ),
        migrations.RemoveIndex(
            model_name='aitool',
            name='idx_aitool_order',
        ),
        migrations.RemoveIndex(
            model_name='blogcategory',
            name='idx_blogcat_visible_order',
        ),
        migrations.RemoveIndex(
            model_name='cybersecurityresource',
            name='idx_cyber_type_visible',
        ),
        migrations.RemoveIndex(
            model_name='cybersecurityresource',
            name='idx_cyber_featured',
        ),
        migrations.RemoveIndex(
            model_name='cybersecurityresource',
            name='idx_cyber_urgency',
        ),
        migrations.RemoveIndex(
            model_name='personalinfo',
            name='idx_personal_key',
        ),
        migrations.RemoveIndex(
            model_name='personalinfo',
            name='idx_personal_visible_order',
        ),
        migrations.RemoveIndex(
            model_name='sociallink',
            name='idx_social_platform_visible',
        ),
        migrations.RemoveIndex(
            model_name='sociallink',
            name='idx_social_primary',
        ),
        migrations.RemoveIndex(
            model_name='sociallink',
            name='idx_social_order',
        ),
    ]
