# Generated by Django 5.2.5 on 2025-08-27 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sociallink_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='AI aracının adı', max_length=100)),
                ('description', models.TextField(help_text='AI aracının kısa açıklaması')),
                ('url', models.URLField(help_text="AI aracının web sitesi URL'si")),
                ('category', models.CharField(choices=[('general', 'Genel Platformlar & Sohbet'), ('visual', 'Görsel & Tasarım'), ('video', 'Video & Animasyon'), ('audio', 'Ses, Müzik & Podcast'), ('text', 'Yazı & İçerik Üretimi'), ('code', 'Kodlama & Geliştirme'), ('research', 'Araştırma & Akademik'), ('productivity', 'Verimlilik & Yardımcı Araçlar'), ('other', 'Diğer')], default='general', help_text='AI aracının kategorisi', max_length=20)),
                ('icon_url', models.URLField(blank=True, help_text="AI aracının ikonu URL'si (opsiyonel)", null=True)),
                ('image', models.ImageField(blank=True, help_text='AI aracının görseli', null=True, upload_to='ai_tools/')),
                ('is_featured', models.BooleanField(default=False, help_text='Öne çıkan araç olarak işaretle')),
                ('is_free', models.BooleanField(default=True, help_text='Ücretsiz mi?')),
                ('rating', models.FloatField(default=0.0, help_text='Kişisel değerlendirme (0-5)')),
                ('tags', models.CharField(blank=True, help_text='Virgülle ayrılmış etiketler (AI, GPT, vs.)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Sıralama (küçük sayılar önce görünür)')),
                ('is_visible', models.BooleanField(default=True, help_text='Site üzerinde görünür mü?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Tool',
                'verbose_name_plural': 'AI Tools',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CybersecurityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kaynak başlığı', max_length=150)),
                ('description', models.TextField(help_text='Kaynağın detaylı açıklaması')),
                ('content', models.TextField(blank=True, help_text='Ana içerik (Markdown destekli)')),
                ('type', models.CharField(choices=[('tool', 'Güvenlik Aracı'), ('threat', 'Tehdit Türü'), ('standard', 'Standart/Framework'), ('practice', 'En İyi Uygulama'), ('news', 'Güncel Haber/Tehdit'), ('tutorial', 'Eğitim/Rehber'), ('certification', 'Sertifikasyon'), ('other', 'Diğer')], default='tool', help_text='Kaynak türü', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Başlangıç'), ('intermediate', 'Orta'), ('advanced', 'İleri'), ('expert', 'Uzman')], default='beginner', help_text='Zorluk seviyesi', max_length=20)),
                ('url', models.URLField(blank=True, help_text="İlgili web sitesi URL'si", null=True)),
                ('image', models.ImageField(blank=True, help_text='Kaynak görseli', null=True, upload_to='cybersecurity/')),
                ('tags', models.CharField(blank=True, help_text='Virgülle ayrılmış etiketler (malware, firewall, vs.)', max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Öne çıkan kaynak olarak işaretle')),
                ('is_urgent', models.BooleanField(default=False, help_text='Acil/güncel tehdit mi?')),
                ('severity_level', models.IntegerField(choices=[(1, 'Düşük'), (2, 'Orta'), (3, 'Yüksek'), (4, 'Kritik')], default=1, help_text='Önem/ciddiyet seviyesi')),
                ('order', models.IntegerField(default=0, help_text='Sıralama')),
                ('is_visible', models.BooleanField(default=True, help_text='Site üzerinde görünür mü?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cybersecurity Resource',
                'verbose_name_plural': 'Cybersecurity Resources',
                'ordering': ['-is_urgent', '-severity_level', 'type', 'order', 'title'],
            },
        ),
    ]
