# Generated by Django 5.2.5 on 2025-09-02 00:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blogcategory_musicplaylist_spotifycurrenttrack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Proje başlığı', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL için benzersiz slug (otomatik oluşturulur)', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Proje açıklaması')),
                ('detailed_description', models.TextField(blank=True, help_text='Detaylı proje açıklaması (Markdown destekli)')),
                ('image', models.ImageField(blank=True, help_text='Proje ana görseli', null=True, upload_to='projects/')),
                ('gallery_images', models.JSONField(blank=True, help_text="Proje galeri görselleri URL'leri (JSON array)", null=True)),
                ('tech_stack', models.JSONField(default=list, help_text='Kullanılan teknolojiler (JSON array)')),
                ('github_url', models.URLField(blank=True, help_text="GitHub repository URL'si", null=True)),
                ('live_url', models.URLField(blank=True, help_text="Canlı proje URL'si", null=True)),
                ('demo_url', models.URLField(blank=True, help_text="Demo URL'si", null=True)),
                ('status', models.CharField(choices=[('planning', 'Planlama'), ('development', 'Geliştirme'), ('testing', 'Test'), ('completed', 'Tamamlandı'), ('maintenance', 'Bakım'), ('archived', 'Arşivlendi')], default='planning', help_text='Proje durumu', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Proje başlangıç tarihi', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Proje bitiş tarihi', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Öne çıkan proje olarak işaretle')),
                ('is_open_source', models.BooleanField(default=True, help_text='Açık kaynak proje mi?')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Kolay'), (2, 'Orta'), (3, 'Zor'), (4, 'Uzman'), (5, 'Master')], default=1, help_text='Proje zorluk seviyesi')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Görüntülenme sayısı')),
                ('order', models.IntegerField(default=0, help_text='Sıralama (küçük sayılar önce görünür)')),
                ('is_visible', models.BooleanField(default=True, help_text='Site üzerinde görünür mü?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
    ]
