# Generated by Django 5.2.5 on 2025-09-02 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sertifika Adı')),
                ('issuer', models.CharField(max_length=200, verbose_name='Veren Kurum')),
                ('certificate_type', models.CharField(choices=[('certification', 'Sertifikasyon'), ('course', 'Kurs'), ('diploma', 'Diploma'), ('award', 'Ödül'), ('license', 'Lisans')], default='certification', max_length=20, verbose_name='Sertifika Türü')),
                ('issue_date', models.DateField(verbose_name='Veriliş Tarihi')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Son Geçerlilik Tarihi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('skills_gained', models.JSONField(blank=True, default=list, verbose_name='Kazanılan Beceriler')),
                ('certificate_url', models.URLField(blank=True, verbose_name="Sertifika URL'si")),
                ('verification_url', models.URLField(blank=True, verbose_name="Doğrulama URL'si")),
                ('certificate_file', models.FileField(blank=True, upload_to='certificates/', verbose_name='Sertifika Dosyası')),
                ('certificate_image', models.ImageField(blank=True, upload_to='certificates/images/', verbose_name='Sertifika Görseli')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='Kimlik Numarası')),
                ('grade_score', models.CharField(blank=True, max_length=50, verbose_name='Not/Puan')),
                ('duration_hours', models.IntegerField(blank=True, null=True, verbose_name='Süre (Saat)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkarılsın mı?')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Görünür mü?')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Sertifika',
                'verbose_name_plural': 'Sertifikalar',
                'ordering': ['-is_featured', 'order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000, verbose_name='Orijinal URL')),
                ('short_code', models.CharField(max_length=10, unique=True, verbose_name='Kısa Kod')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('click_count', models.IntegerField(default=0, verbose_name='Tıklama Sayısı')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Son Erişim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Kullanma Tarihi')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='Şifre (isteğe bağlı)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Kısa URL',
                'verbose_name_plural': "Kısa URL'ler",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Beceri Adı')),
                ('category', models.CharField(choices=[('programming', 'Programlama'), ('framework', 'Framework'), ('database', 'Veritabanı'), ('tools', 'Araçlar'), ('cloud', 'Bulut'), ('security', 'Güvenlik'), ('design', 'Tasarım'), ('soft', 'Kişisel Beceriler'), ('language', 'Dil'), ('other', 'Diğer')], max_length=20, verbose_name='Kategori')),
                ('proficiency_level', models.IntegerField(choices=[(1, 'Başlangıç'), (2, 'Temel'), (3, 'Orta'), (4, 'İleri'), (5, 'Uzman')], default=3, verbose_name='Yeterlilik Seviyesi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Deneyim Yılı')),
                ('icon_class', models.CharField(blank=True, max_length=100, verbose_name='Icon CSS Sınıfı')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Renk (Hex)')),
                ('projects_count', models.IntegerField(default=0, verbose_name='Proje Sayısı')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkarılsın mı?')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Görünür mü?')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('certificates', models.ManyToManyField(blank=True, to='main.certificate', verbose_name='İlgili Sertifikalar')),
            ],
            options={
                'verbose_name': 'Beceri',
                'verbose_name_plural': 'Beceriler',
                'ordering': ['category', '-is_featured', 'order', 'name'],
            },
        ),
    ]
