# Generated by Django 5.1 on 2025-09-08 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_errorlog_performancemetric_webpushsubscription_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        help_text="Short code for the URL", max_length=10, unique=True
                    ),
                ),
                (
                    "original_url",
                    models.URLField(help_text="Original long URL", max_length=2000),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for the link",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Optional password protection",
                        max_length=50,
                    ),
                ),
                (
                    "click_count",
                    models.IntegerField(default=0, help_text="Number of clicks"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the short URL is active"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Expiration date (optional)", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Short URL",
                "verbose_name_plural": "Short URLs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="performancemetric",
            index=models.Index(
                fields=["timestamp", "metric_type"],
                name="main_perfor_timesta_c14c9c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shorturl",
            index=models.Index(
                fields=["short_code"], name="main_shortu_short_c_aa9931_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shorturl",
            index=models.Index(
                fields=["is_active", "expires_at"],
                name="main_shortu_is_acti_1c766c_idx",
            ),
        ),
    ]
