# Generated by Django 5.1 on 2025-09-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_shorturl_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aitool',
            index=models.Index(fields=['category', 'is_visible', 'order'], name='main_aitool_categor_035a57_idx'),
        ),
        migrations.AddIndex(
            model_name='aitool',
            index=models.Index(fields=['is_featured', '-created_at'], name='main_aitool_is_feat_569236_idx'),
        ),
        migrations.AddIndex(
            model_name='aitool',
            index=models.Index(fields=['is_visible', 'category'], name='main_aitool_is_visi_e40875_idx'),
        ),
        migrations.AddIndex(
            model_name='aitool',
            index=models.Index(fields=['rating', 'is_visible'], name='main_aitool_rating_73948a_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['is_visible', 'order'], name='main_blogca_is_visi_f57927_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['name'], name='main_blogca_name_2ff93e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-published_at'], name='main_blogpo_status_3ba03e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category', 'status', '-published_at'], name='main_blogpo_categor_5b48d7_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author', '-published_at'], name='main_blogpo_author__1939c0_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_featured', 'status'], name='main_blogpo_is_feat_34b250_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='main_blogpo_slug_b48d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='cybersecurityresource',
            index=models.Index(fields=['type', 'is_visible', 'order'], name='main_cybers_type_64bf64_idx'),
        ),
        migrations.AddIndex(
            model_name='cybersecurityresource',
            index=models.Index(fields=['is_urgent', '-severity_level'], name='main_cybers_is_urge_69b790_idx'),
        ),
        migrations.AddIndex(
            model_name='cybersecurityresource',
            index=models.Index(fields=['is_featured', '-created_at'], name='main_cybers_is_feat_112579_idx'),
        ),
        migrations.AddIndex(
            model_name='cybersecurityresource',
            index=models.Index(fields=['difficulty', 'type'], name='main_cybers_difficu_43fb58_idx'),
        ),
        migrations.AddIndex(
            model_name='musicplaylist',
            index=models.Index(fields=['is_visible', 'order'], name='main_musicp_is_visi_402303_idx'),
        ),
        migrations.AddIndex(
            model_name='musicplaylist',
            index=models.Index(fields=['platform', 'is_visible'], name='main_musicp_platfor_9dcc5f_idx'),
        ),
        migrations.AddIndex(
            model_name='musicplaylist',
            index=models.Index(fields=['is_featured', '-created_at'], name='main_musicp_is_feat_9a2342_idx'),
        ),
        migrations.AddIndex(
            model_name='personalinfo',
            index=models.Index(fields=['is_visible', 'order'], name='main_person_is_visi_377110_idx'),
        ),
        migrations.AddIndex(
            model_name='personalinfo',
            index=models.Index(fields=['key'], name='main_person_key_a4d39e_idx'),
        ),
        migrations.AddIndex(
            model_name='personalinfo',
            index=models.Index(fields=['type', 'is_visible'], name='main_person_type_dec8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='sociallink',
            index=models.Index(fields=['is_visible', 'order'], name='main_social_is_visi_00c2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='sociallink',
            index=models.Index(fields=['platform', 'is_visible'], name='main_social_platfor_da02cd_idx'),
        ),
        migrations.AddIndex(
            model_name='sociallink',
            index=models.Index(fields=['is_primary'], name='main_social_is_prim_5b68d7_idx'),
        ),
        migrations.AddIndex(
            model_name='usefulresource',
            index=models.Index(fields=['category', 'is_visible', 'order'], name='main_useful_categor_9eedd8_idx'),
        ),
        migrations.AddIndex(
            model_name='usefulresource',
            index=models.Index(fields=['type', 'category'], name='main_useful_type_2271d1_idx'),
        ),
        migrations.AddIndex(
            model_name='usefulresource',
            index=models.Index(fields=['is_featured', '-created_at'], name='main_useful_is_feat_79522e_idx'),
        ),
        migrations.AddIndex(
            model_name='usefulresource',
            index=models.Index(fields=['is_free', 'category'], name='main_useful_is_free_f65545_idx'),
        ),
        migrations.AddIndex(
            model_name='usefulresource',
            index=models.Index(fields=['rating', 'is_visible'], name='main_useful_rating_b8fe1f_idx'),
        ),
    ]
