# Generated by Django 5.1 on 2025-09-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_aitool_main_aitool_categor_035a57_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='personalinfo',
            new_name='personal_vis_order',
            old_name='main_person_is_visi_377110_idx',
        ),
        migrations.RenameIndex(
            model_name='personalinfo',
            new_name='personal_key',
            old_name='main_person_key_a4d39e_idx',
        ),
        migrations.RenameIndex(
            model_name='personalinfo',
            new_name='personal_type_vis',
            old_name='main_person_type_dec8f1_idx',
        ),
        migrations.RenameIndex(
            model_name='sociallink',
            new_name='social_vis_order',
            old_name='main_social_is_visi_00c2a5_idx',
        ),
        migrations.RenameIndex(
            model_name='sociallink',
            new_name='social_plat_vis',
            old_name='main_social_platfor_da02cd_idx',
        ),
        migrations.RenameIndex(
            model_name='sociallink',
            new_name='social_primary',
            old_name='main_social_is_prim_5b68d7_idx',
        ),
        migrations.AddIndex(
            model_name='personalinfo',
            index=models.Index(fields=['is_visible', 'type', 'order'], name='personal_vis_type_ord'),
        ),
        migrations.AddIndex(
            model_name='personalinfo',
            index=models.Index(fields=['-updated_at'], name='personal_updated_desc'),
        ),
        migrations.AddIndex(
            model_name='sociallink',
            index=models.Index(fields=['platform'], name='social_platform'),
        ),
        migrations.AddIndex(
            model_name='sociallink',
            index=models.Index(fields=['is_visible', 'platform', 'order'], name='social_vis_plat_ord'),
        ),
    ]
