# Generated by Django 5.2.5 on 2025-08-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_tool_options_tool_icon_url_tool_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image/screenshot for this tool', null=True, upload_to='tools/'),
        ),
    ]
