# Generated by Django 5.2.5 on 2025-09-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_tool_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='pricing',
        ),
        migrations.AddField(
            model_name='tool',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='Link to documentation', null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL', null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='platform_compatibility',
            field=models.TextField(blank=True, help_text='Platform compatibility information', null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='popularity_score',
            field=models.FloatField(default=0.0, help_text='Popularity score for ranking'),
        ),
        migrations.AddField(
            model_name='tool',
            name='pricing_details',
            field=models.CharField(default='', help_text='Detailed pricing information', max_length=100),
        ),
        migrations.AddField(
            model_name='tool',
            name='pricing_type',
            field=models.CharField(default='unknown', help_text='Type of pricing (free, paid, freemium, etc.)', max_length=20),
        ),
    ]
