# Generated by Django 5.2.5 on 2025-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_remove_tool_pricing_tool_documentation_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='documentation_url',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='platform_compatibility',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='popularity_score',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='pricing_details',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='pricing_type',
        ),
        migrations.AddField(
            model_name='tool',
            name='pricing',
            field=models.CharField(blank=True, help_text="Pricing info (e.g., 'Free', '$10/month', 'Freemium')", max_length=50),
        ),
    ]
