# Generated by Django 5.2.5 on 2025-08-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['category', 'title'], 'verbose_name': 'Tool', 'verbose_name_plural': 'Tools'},
        ),
        migrations.AddField(
            model_name='tool',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to an icon/logo for this tool', null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Whether this tool is visible on the site'),
        ),
        migrations.AddField(
            model_name='tool',
            name='last_updated',
            field=models.DateField(blank=True, help_text='When this tool info was last updated', null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='pricing',
            field=models.CharField(blank=True, help_text="Pricing info (e.g., 'Free', '$10/month', 'Freemium')", max_length=50),
        ),
        migrations.AddField(
            model_name='tool',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Personal rating from 1-5 stars', null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Development', 'Development'), ('Design', 'Design'), ('Framework', 'Framework'), ('Database', 'Database'), ('DevOps', 'DevOps'), ('Testing', 'Testing'), ('Security', 'Security'), ('Productivity', 'Productivity'), ('API', 'API'), ('Cloud', 'Cloud'), ('Mobile', 'Mobile'), ('AI/ML', 'AI/ML'), ('Analytics', 'Analytics'), ('Other', 'Other')], help_text='Category this tool belongs to', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(help_text='Detailed description of what this tool does'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark as favorite tool (will appear on home page)'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tags',
            field=models.JSONField(blank=True, help_text='List of tags for this tool (as JSON array)', null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='title',
            field=models.CharField(help_text='Name of the tool or resource', max_length=200),
        ),
        migrations.AlterField(
            model_name='tool',
            name='url',
            field=models.URLField(help_text='Official URL or link to the tool'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['category', 'title'], name='tools_tool_categor_5f72a3_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_favorite', '-created_at'], name='tools_tool_is_favo_b11da6_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_visible', 'category'], name='tools_tool_is_visi_d1b99d_idx'),
        ),
    ]
