name: Deploy to Railway

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    name: Railway Deployment
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Railway CLI and deploy
        uses: railwayapp/railway-action@v3
        with:
          service: portfolio-prod
          environment: production
          command: up
